language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install now
script:
  - npm run lint
  - ./node_modules/.bin/now --public --token=$token
  - ./node_modules/.bin/now ln --token=$token
