language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run lint
before_deploy:
  - npm install -g now
deploy:
  provider: script
  script:
    - now --public --token=$token
    - now ln --token=$token