language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run lint
deploy:
  provider: script
  script:
    - npm install now
    - ./node_modules/.bin/now --public --token=$token
    - ./node_modules/.bin/now ln --token=$token
