language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run lint
before_deploy:
  - npm run $(npm bin) now -v
deploy:
  - skip_cleanup: true
  - provider: script
    script: npm run deploy
    on:
      all_branches: true
  - provider: script
    script: npm run add_alias
    on:
      branch: master