language: node_js
node_js:
  - "node"
before_install:
  - npm install -g now
install:
  - npm install
script:
  - npm run lint
deploy:
  provider: script
  script: npm run publish
  on:
    all_branches: true
  provider: script
  script: npm run publish
  on:
    branch: master